# Site settings
title: "Introduction to Scientific and Engineering Computing - ITU Economics"
description: "BIL 113E Open Course Materials for MATLAB, Python and R"
baseurl: "/bil113e"
url: "http://itueconomics.github.io"
twitter_username: ituecon
github_username:  itueconomics

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag