# Site settings
title: "Introduction to Scientific and Engineering Computing - ITU Economics Open Course"
description: "BIL113E (Introduction to Scientific and Engineering Computing) course materials"
baseurl: "/bil113e"
url: "http://itueconomics.github.io"
twitter_username: ituecon
github_username:  itueconomics

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag